import "../scss/main.scss"
import type { Metadata } from "next"
import { Header } from "@/components/header"
import { Transition } from "@/components/transition/transition"
import { ViewTransitions } from "next-view-transitions"

export const metadata: Metadata = {
  title: "Viewing",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body>
          <Header />
          <Transition>{children}</Transition>
        </body>
      </html>
    </ViewTransitions>
  )
}
