import "../scss/main.scss"
import type { Metadata } from "next"
// import Categories from "./categories/page"
import { Hero } from "@/components/hero"
import { Header } from "@/components/header"
import { Categories } from "@/components/categories"

export const metadata: Metadata = {
  title: "Viewing",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
          <Hero />
          {/* <Categories /> */}
          {children}
        </main>
      </body>
    </html>
  )
}
